import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv("netflix_titles.csv")
df = df.dropna(subset = ["type","title","director","cast","country","date_added","release_year","rating","duration","listed_in","description"])

type_count = df['type'].value_counts()
plt.figure(figsize=(6,4))
plt.bar(type_count.index,type_count.values , color=["orange","red"])
plt.title("Number of movies v/s TV Shows On Netflix")
plt.xlabel("Type")
plt.ylabel("Count")
plt.tight_layout()
plt.savefig("Movies_vs_Tv_Showes.png")
plt.show()

rating_counts=df['rating'].value_counts()
plt.figure(figsize=(6,2))
plt.pie(rating_counts,labels=rating_counts.index,autopct="%1.1f%%",startangle=90)
plt.title("Percentage of Content Ratings")
plt.tight_layout()
plt.savefig("Content_Ratings_pic.png")
plt.show()

movie_df = df[df['type'] == 'Movie'].copy()
movie_df['duration_int'] = movie_df['duration'].str.replace(' min', '', regex=False)
movie_df['duration_int'] = pd.to_numeric(movie_df['duration_int'], errors='coerce')
movie_df = movie_df.dropna(subset=['duration_int'])
plt.figure(figsize=(8,6))
plt.hist(movie_df['duration_int'], bins=30, color='purple', edgecolor='black')
plt.title('Distribution of Movie Duration')
plt.xlabel('Duration (minutes)')
plt.ylabel('Number of Movies')
plt.tight_layout()
plt.savefig("Movie_Duration_Histogram.png")
plt.show()

release_count = df['release_year'].value_counts().sort_index()
plt.figure(figsize=(10,6))
plt.scatter(release_count.index,release_count.values,color='green')
plt.title('Release Year vs Number of Shows')
plt.xlabel('Release Year')
plt.ylabel('Number of Shows')
plt.tight_layout()
plt.savefig("Release_Year_Scatter.png")
plt.show()

country_counts=df['country'].value_counts().head(10)
plt.figure(figsize=(8,6))
plt.barh(country_counts.index,country_counts.values,color=['purple','white'])
plt.title("Top 10 Countries with the Highest Number of Shows ")
plt.xlabel("Number of Shows")
plt.ylabel("Country")
plt.tight_layout()
plt.savefig("Top_10_Countries.png")
plt.show()

released_count = df['release_year'].value_counts().sort_index()
plt.figure(figsize=(10,6))
plt.plot(released_count.index,released_count.values,color='green')
plt.title('Release Year vs Number of Shows')
plt.xlabel('Release Year')
plt.ylabel('Number of Shows')
plt.tight_layout()
plt.savefig("Released_Year_Scatter.png")
plt.show()



content_by_year = df.groupby(['release_year','type']).size().unstack().fillna(0)
fig ,ax = plt.subplots(1,2, figsize=(12,5))
ax[0].plot(content_by_year.index , content_by_year['Movie'],color='blue')
ax[0].set_title("Movies Released Per Year")
ax[0].set_xlabel("Year")
ax[0].set_ylabel("Number of Movies")

ax[1].plot(content_by_year.index , content_by_year['TV Show'],color='orange')
ax[1].set_title("TV Shows Released Per Year")
ax[1].set_xlabel("Year")
ax[1].set_ylabel("Number of TV Shows")

fig.suptitle("Camparsion of Movies and TV Shows released Per Year")
plt.tight_layout()
plt.savefig("Movies_Tv_Shows_Camaparsion.png")
plt.show()